### PR TITLE
CodeReview Request

### PR DESCRIPTION
**Pull request by Usagib**

### CODE REVIEW

**Comment by Usagib** [comment]
Hello Team!, finished modifications on this project, sending it for code review

**Comment by shshamim63** [comment]
## Status :red_circle:  [!! Changes Required !!] :red_circle: 
___
Hi @Usagib :wave:,
You have covered most of the task asked by the previous TSE (You were suppose to maintain a PR to get review on this project.). But some simple issues are blocking me to approve this project by now. 
___
#### Please follow the instructions below to complete this project.
___
### :dagger: [Mandatory Changes] :dagger: 
___
1. Why there is a curly brace here? I don't think that is needed. Please remove it. 
https://github.com/Usagib/gitflowenumerableruby/blob/ef621af8ae9371203a028ee0908dead440fcf5c4/script.rb#L39
2. Here, you are comparing with arg, but in the parameter I cannot see it. It should accept a parameter called arg like the my_any?(arg = nil) 
https://github.com/Usagib/gitflowenumerableruby/blob/ef621af8ae9371203a028ee0908dead440fcf5c4/script.rb#L66-L79
3. You have declared in your inject that your final answer will be stored in memory variable. But you have returned memo. What is memo in here? Or you meant memory.
https://github.com/Usagib/gitflowenumerableruby/blob/ef621af8ae9371203a028ee0908dead440fcf5c4/script.rb#L124
___
### :open_hands: [Optional Changes] :open_hands: 
___
I think there is are more room to improve your readme. You can add your linkedin, twitter profile link. A summary about the task you have covered.
___
### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain 
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__Shakhawat Hossain__)

**Comment by Usagib** [comment]
Hello Team!
Modifications Done!
i'll keep one PR for review from now on, thank you for the advice
Happy Coding!

**Comment by Usagib** [comment]
Hello Team!
Modifications Done!
i'll keep one PR for review from now on, thank you for the advice
i added overview to the readme along with my github profile, i'm using this holiday time to complete my networking profiles, i'll add them as soon as i have them updated
Happy Coding!

**Comment by shshamim63** [comment]
## Status :cake: [!! Approved !!] :cake: 
___
Hi @Usagib :wave: ,
It is me again :smile: , Awesome job :clap: . All the methods are functional, covers each edge cases properly. Code Looks neat and clean. In one word `Complete`.
___
### This :+1:  is from me :zap: . You can merge it and don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain 
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](__Shakhawat Hossain__)

**Pull request merged**
